spring:
  application:
    name: fegin-consumer
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
SPRING-CLOUD-PROVIDER:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true # 对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # hystrix时间配置必须大于ribbon超时时间，否则重试机制没有意思
# feign其他配置，例如压缩配置
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048 #压缩大小下限
      mime-types: text/xml,application/xml,application/json # 压缩类型
    response:
      enabled: true
  hystrix:
    enabled: true