spring:
  application:
    name: fegin-consumer
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
SPRING-CLOUD-PROVIDER:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2 # 尝试更换两次实例进行重试
    MaxAutoRetries: 1 # 重试策略先尝试访问首选实例一次，失败后才更换实例访问
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # hystrix时间配置必须大于ribbon超时时间，否则重试机制没有意思
# feign其他配置，例如压缩配置
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048 #压缩大小下限
      mime-types: text/xml,application/xml,application/json # 压缩类型
    response:
      enabled: true