spring:
  application:
    name: spring-cloud-hystrix
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    # fetch-registry: true # \u662F\u5426\u66F4\u65B0\u6E05\u5355
    # registry-fetch-interval-seconds: 30 # \u6E05\u5355\u6BCF\u969430\u79D2\u66F4\u65B0\u4E00\u6B21
