spring:
  application:
    name: api-gateway
server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    provide:
      path: /provide/** # \u6240\u6709http://localhost:8005/provide/**\u8BF7\u6C42\uFF0C\u90FD\u4F1A\u8F6C\u53D1\u5230SPRING-CLOUD-PROVIDER\u670D\u52A1
      serviceId: SPRING-CLOUD-PROVIDER